### ISSUE TITLE
PDB file not found

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion-sdk#25]
When linking FreeOrion, I get a bunch of missing pdf file warnings:
````
1>freetype255MT.lib(autofit.obj) : warning LNK4099: PDB 'freetype.pdb' was not found with 'freetype255MT.lib(autofit.obj)' or at 'C:\Users\Geoff\Desktop\FreeOrionSDK3\FreeOrion\freetype.pdb'; linking object as if no debug info
````
Might be nice to put it where expected / include in the SDK.

**Comment by adrianbroher** [comment]
The latest commit should fix this issue.

When https://ci.appveyor.com/project/freeorion/freeorion-sdk/build/ci-364 is done building you can download an updated SDK under the `artifact` tab.  Could you please provide feedback if the updated version fixes the issue you described?

**Comment by Vezzra** [comment]
Just tested this updated SDK on my Windows machine, and I still get these warnings.

**Comment by adrianbroher** [comment]
I'm not knowledgeable enough in this area to pin down the cause of the error message.  Any ideas?

**Comment by adrianbroher** [comment]
Also should this block the release of the SDK v4 release?  The impact fixed dependency regarding openssl and python, which renders the CI built SDK download relatively useless is quite serve.

**Comment by geoffthemedio** [comment]
I tried the build twice, and it failed both times. I then tried a third time, redirecting the build log to a text file, and it worked without errors.

Resulting .zip is "FreeOrionSDK_3_MSVC-v140.zip". I was expecting 4. Is that only incremented when released?

Testing it now...

**Comment by adrianbroher** [comment]
> Resulting .zip is "FreeOrionSDK_3_MSVC-v140.zip". I was expecting 4. Is that only incremented when released?

The build number is only incremented when the [DIST_VERSION][1] variable is changed.  This is intentional.

[1]: https://github.com/freeorion/freeorion-sdk/blob/master/CMakeLists.txt#L11

**Comment by geoffthemedio** [comment]
I don't see a freetype*.pdb in the SDK directories

**Comment by Vezzra** [comment]
@adrianbroher:

> Also should this block the release of the SDK v4 release?

No. As you said, there are fixes that are quite important and long overdue for release. So I definitely vote for doing the v4 release of the SDK ASAP.

**Comment by geoffthemedio** [comment]
I think this is long-since fixed... at least there are various .pdb files in the SDK now.
