### ISSUE TITLE
[mac-support branch] Current layout of SDK as produced by cmake

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion-sdk#6]
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/194969/cmake-sdk-layout.txt.zip)

**Comment by adrianbroher** [comment]
I pushed some commits that should address most issues.

Could you recreate a new layout file with those changes?

You need to call `make clean` to clean up the build artifacts before building again.

**Comment by Vezzra** [comment]
> You need to call make clean to clean up the build artifacts before building again.

I always delete the entire contents of the build directory before making a new try. A bit radical, I know, but this makes sure that I get an absolutely clean start each time. :wink: 

Here is the new layout:
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/195294/cmake-sdk-layout.txt.zip)

One thing I noticed immediately: the Vorbis.framework hasn't been copied to the INSTALL/dep/lib folder like the Ogg.framework has. It has been built though, just the copy step didn't happen.

**Comment by adrianbroher** [comment]
Could you please try again with the latest commits? Now either the Ogg framework should be installed in the Frameworks directory or it will not be installed at all.

**Comment by Vezzra** [comment]
Now I get an error:
```
CMake Error at CMakeLists.txt:109 (install):
  install TARGETS given no FRAMEWORK DESTINATION for shared library FRAMEWORK
  target "ogg".


-- Configuring incomplete, errors occurred!
See also "/Users/user/SoftwareProjekte/FO/sdk/build/libogg-prefix/src/libogg-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [libogg-prefix/src/libogg-stamp/libogg-configure] Error 1
make[1]: *** [CMakeFiles/libogg.dir/all] Error 2
make: *** [all] Error 2
```
I've also attached the CMakeOutput.log:
[CMakeOutput.log.zip](https://github.com/freeorion/freeorion-sdk/files/195753/CMakeOutput.log.zip)

**Comment by adrianbroher** [comment]
Meh.  Well, that shows at least that the FRAMEWORK DESTINATION parameter IS required.  Try with the latest commit.

**Comment by Vezzra** [comment]
Um...
```
[ 50%] Performing configure step for 'libvorbis'
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring vorbis 1.3.5
-- Could NOT find OGG (missing:  OGG_INCLUDE_DIRS OGG_LIBRARIES) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OGG_INCLUDE_DIRS
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
   used as include directory in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib
OGG_LIBRARIES
    linked by target "vorbis" in directory /Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/lib

-- Configuring incomplete, errors occurred!
See also "/Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [libvorbis-prefix/src/libvorbis-stamp/libvorbis-configure] Error 1
make[1]: *** [CMakeFiles/libvorbis.dir/all] Error 2
make: *** [all] Error 2
```
[CMakeOutput.log.zip](https://github.com/freeorion/freeorion-sdk/files/196974/CMakeOutput.log.zip)

**Comment by adrianbroher** [comment]
Vorbis now doesn't find ogg because it is a framework now, nothing to worry about.  However, is the Ogg Framework now at the right location and builds properly?

**Comment by Vezzra** [comment]
Yep, builds successfully and I get a "Ogg.framework" in the "Frameworks" folder. No Ogg libs and include folders anywhere else. Looks good :smiley:

**Comment by adrianbroher** [comment]
> No Ogg libs and include folders anywhere else. Now that's what I want to hear. :+1: 

I've added another commit to fix the `Could NOT find OGG (missing:  OGG_INCLUDE_DIRS OGG_LIBRARIES)` issue.  Please check if the build now works properly.

**Comment by Vezzra** [comment]
It does. New layout:
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/197517/cmake-sdk-layout.txt.zip)

**Comment by adrianbroher** [comment]
Added another set of commits. Now vorbis should be installed as Framework. Also SDL2 should be build and installed as framework (maybe).

Took some time because I was struggling with the SDL2 mercurial repository.

**Comment by Vezzra** [comment]
Got an error in the configuring SDL2 step, cmake complained that no FRAMEWORK DESTINATION has been set in line 1289 in "sdl-prefix/src/sdl/CMakeLists.txt", which is the following code block:
```
install(TARGETS ${_INSTALL_LIBS}
  LIBRARY DESTINATION "lib${LIB_SUFFIX}"
  ARCHIVE DESTINATION "lib${LIB_SUFFIX}")
```
Adding `FRAMEWORK DESTINATION "Frameworks"` here, so that we get:
```
install(TARGETS ${_INSTALL_LIBS}
  LIBRARY DESTINATION "lib${LIB_SUFFIX}"
  ARCHIVE DESTINATION "lib${LIB_SUFFIX}"
  FRAMEWORK DESTINATION "Frameworks")
```
...solved the issue. Don't know why that's needed here, because, from what I've seen, the FRAMEWORK DESTINATION does get set for non Windows platforms on line 1307, but what do I know :wink: 

You're probably going to adjust my fix, so I just post it here.

After that the build succeeds, new layout:
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/199277/cmake-sdk-layout.txt.zip)

As you can see, the Vorbis framework has been produced and placed correctly, no Vorbis stuff anywhere else.

However, things didn't go as smoothly with SDL2. I did get a framework at the right location, but the header files have not been placed at the proper location within the framework, but in the "include" folder instead. "sdl2-config" has been placed in "bin", don't know if that's correct. And this ominous "sdl2.m4" (whatever that is) has also still been placed in "share/aclocal".

**Comment by adrianbroher** [comment]
> Don't know why that's needed here, because, from what I've seen, the FRAMEWORK DESTINATION does get set for non Windows platforms on line 1307, but what do I know.

You got that right so far, and I don't even know why that is needed there.  To be honest the upstream CMakelists.txt for SDL isn't the prettiest one or easy to read so It's maybe because of some convoluted conditional that doesn't write the FRAMEWORK DESTINATION at the proper time.

> As you can see, the Vorbis framework has been produced and placed correctly, no Vorbis stuff anywhere else.

Comparing this with the current one I see the current one is called `vorbis.framework` while the generated one is called `Vorbis.framework`.  While I assume that this should not matter because of the case insensitive filesystem are you aware of some best practice for naming frameworks? Taking a look at the [OS X Frameworks][] it seems like CamelCase is the preferred way of naming those.

> However, things didn't go as smoothly with SDL2.

Yeah, I forgot to add a PUBLIC_HEADER property to declare what files are public headers.

> "sdl2-config" has been placed in "bin"

At least the Framework in the current SDK doesn't contain this (probably because it is superfluous by design, as Frameworks provide all the config data necessary).  Do you know what would be the correct place of a utility binary within a framework?

> And this ominous "sdl2.m4" (whatever that is) has also still been placed in "share/aclocal".

That's a utility script in M4 language used by autotools.  When building a framework it shouldn't be installed at all so I need to if that out.

[OS Frameworks]: https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html

**Comment by Vezzra** [comment]
> are you aware of some best practice for naming frameworks? Taking a look at the OS X Frameworks it seems like CamelCase is the preferred way of naming those.

No, I'm not aware of any recommendations/rules for that. However, there is actually a HFS+ variant you can use when formatting a Mac volume which actually *is* case-sensitive, so I'd stick with the "official" naming.

> Do you know what would be the correct place of a utility binary within a framework?

No, but looking at the OpenGL and Python frameworks (they have some additional binaries that look like utilities) apparently the usual practice is to put them in a subfolder that is located in the same directory as the main library binary ("whatever.framework/Versions/version-identifier/"). OpenGL has a subfolder there named "Libraries", which contains additional binaries. Python has a subfolder "bin", which contains the 2to3, idle, pydoc etc. binaries, then there is a "Extras" folder which in turn contains another "bin" directory with another bunch of binaries (cftp, ckeygen, conch, f2py, etc.).

As "sdl2-config" has been placed in "bin", I'd make a "bin" subfolder in the folder containing the "SDL2" binary, and put sld2-config there. But I don't really now what I'm talking about... :wink:

**Comment by adrianbroher** [comment]
Added another fix for SDL. Now the framework should be complete. I also didn't install any of the other utility files related to SDL as they are not needed for the framework usage.

**Comment by Vezzra** [comment]
Had to fix a typo (already committed 9999d02154cfcb233db0100f520b086079e0de20), then again the complaint:
```
CMake Error at CMakeLists.txt:1325 (install):
  install TARGETS given no FRAMEWORK DESTINATION for shared library FRAMEWORK
  target "SDL2".
```
...this time for the install statement at line 1325:

`install(TARGETS SDL2 RUNTIME DESTINATION bin)`

Changing that to:
```
  install(TARGETS SDL2
    RUNTIME DESTINATION bin
    FRAMEWORK DESTINATION "Frameworks")
```
...again solved the issue, but that's of course just a "dirty hack". That part gets applied if we are on Windows or a framework is being built (see line 1307), the actual fix will have to be a bit more thorough.

After that the build succeeded, new layout:
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/200162/cmake-sdk-layout.txt.zip)

This time the SDL2 headers no longer got copied to the "include" folder, unfortunately neither into the framework - apparently they went to Nirwana.

Ok, I've to call it a day. Won't have much time over the weekend, but should be able to get something done again on Monday. Cheers! :smiley:

**Comment by Vezzra** [comment]
Just had a bit time, so tried to build with the latest commit. Got an error:
```
[  3%] Performing patch step for 'sdl'
patching file CMakeLists.txt
patching file CMakeLists.txt
patching file CMakeLists.txt
patching file CMakeLists.txt
Hunk #3 succeeded at 1303 with fuzz 2.
patching file CMakeLists.txt
Hunk #1 FAILED at 1301.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
make[2]: *** [sdl-prefix/src/sdl-stamp/sdl-patch] Error 1
make[1]: *** [CMakeFiles/sdl.dir/all] Error 2
make: *** [all] Error 2
```
Contents of "CMakeLists.txt.rej":
```
***************
*** 1301,1306 ****
  install(TARGETS ${_INSTALL_LIBS}
    LIBRARY DESTINATION "lib${LIB_SUFFIX}"
    ARCHIVE DESTINATION "lib${LIB_SUFFIX}"
    PUBLIC_HEADER DESTINATION DESTINATION include/SDL2)
  
  if((NOT WINDOWS OR CYGWIN) AND (NOT BUILD_FRAMEWORK))
--- 1301,1307 ----
  install(TARGETS ${_INSTALL_LIBS}
    LIBRARY DESTINATION "lib${LIB_SUFFIX}"
    ARCHIVE DESTINATION "lib${LIB_SUFFIX}"
+   FRAMEWORK DESTINATION "Frameworks"
    PUBLIC_HEADER DESTINATION DESTINATION include/SDL2)
  
  if((NOT WINDOWS OR CYGWIN) AND (NOT BUILD_FRAMEWORK))
```

**Comment by adrianbroher** [comment]
Yeah, I didn't update all following patches after `sdl2-3-add_target_properties_to_generate_macosx_framework.patch` so they still contained some different context lines, making patch spew.  Fixed that in the latest commit.

**Comment by Vezzra** [comment]
New layout:
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/201267/cmake-sdk-layout.txt.zip)

The SDL2 header files still don't get installed in the framework (nor anywhere else).

**Comment by adrianbroher** [comment]
That's because there is another nastiness of CMake I wasn't aware of.  To install the header files in a framework you need to add the header files to the add_{library,executable} command.  The latest commit should finally fix the installation.

**Comment by Vezzra** [comment]
Yup, looks good:
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/201464/cmake-sdk-layout.txt.zip)

**Comment by adrianbroher** [comment]
Continuing with the python framework support.

I assume until this hasn't been fixed I can't return to the fun stuff.

**Comment by Vezzra** [comment]
Getting this error repeatedly when building boost now:
```
In file included from libs/python/src/numeric.cpp:6:
In file included from ./boost/python/numeric.hpp:8:
In file included from ./boost/python/detail/prefix.hpp:13:
./boost/python/detail/wrap_python.hpp:75:10: fatal error: 'patchlevel.h' file not found
#include <patchlevel.h>
         ^
1 error generated.
```

> I assume until this hasn't been fixed I can't return to the fun stuff.

What? CMakeifying the SDKs isn't fun? Geee... :wink:

**Comment by adrianbroher** [comment]
> Getting this error repeatedly when building boost now.

Lets ignore that for now. What about the Python framework layout?

**Comment by Vezzra** [comment]
> What about the Python framework layout?

[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/211914/cmake-sdk-layout.txt.zip)

As you can see, not so good. No Python framework at all, but all the Python stuff in the same locations as before. And Python man pages in a "share" subfolder. Not quite there yet. ;)

**Comment by adrianbroher** [comment]
The previous version had the FRAMEWORK DESTINATION part of the target install command missing. Try with the latest commit.

**Comment by Vezzra** [comment]
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/212574/cmake-sdk-layout.txt.zip)

Same as before...

**Comment by adrianbroher** [comment]
Give it another try, the python dep was built as static library, which doesn't work for frameworks.

**Comment by Vezzra** [comment]
[cmake-sdk-layout.txt.zip](https://github.com/freeorion/freeorion-sdk/files/212871/cmake-sdk-layout.txt.zip)

This time, the framework did get created. However, not in the "Frameworks", but in the "lib" folder. The Python standard library did not get placed in the framework, but beside it also in the "lib" folder, the headers went into "include". And there is still Python stuff in the "bin" folder. The man pages in "share" are also still there.

But progress has been made 😃

**Comment by adrianbroher** [comment]
Please try again.

**Comment by Vezzra** [comment]
Well, some more progress, the Python framework now is correctly placed in the "Frameworks" folder:
[cmake-sdk-layout.txt](https://github.com/freeorion/freeorion-sdk/files/214321/cmake-sdk-layout.txt)

The other issues however remain: standard library in the "lib" folder, headers in the "include" folder, Python stuff in "bin", man pages in "share" (and the boost build error of course).

**Comment by adrianbroher** [comment]
Can you give me a quick overview of the libraries that are good and the ones that are still problematic?  This issue is getting to long and not working on the issue doesn't help either.

**Comment by adrianbroher** [comment]
I rebased the mac-support branch to the current master to clean up the branch a bit.

**Comment by Vezzra** [comment]
Ok, finally got around to this. To find out how far we got I tried to rerun the build procedure, and for whatever reason an error [we already dealt with above](https://github.com/freeorion/freeorion-sdk/issues/6#issuecomment-203746927) turned up again.

Build log: [build.log.zip](https://github.com/freeorion/freeorion-sdk/files/465994/build.log.zip)
CMakeOutput.log: [CMakeOutput.log.zip](https://github.com/freeorion/freeorion-sdk/files/465995/CMakeOutput.log.zip)

**Comment by Vezzra** [comment]
Sorry for the delay, was a bit swamped with release work...

**Comment by adrianbroher** [comment]
> And for whatever reason an error we already dealt with above turned up again.

:expressionless:  Yeah, probably that got lost while rebasing and sorting out patches AND I forgot how to fix it, ehh…

> Sorry for the delay, was a bit swamped with release work...

No problem, this has no priority.

**Comment by adrianbroher** [comment]
> Ok, finally got around to this. To find out how far we got I tried to rerun the build procedure, and for whatever reason an error we already dealt with above turned up again.

Should be fixed in the latest mac-branch HEAD.

**Comment by Vezzra** [comment]
Lather, rinse, repeat... this time patching some of the cmake files for Python failed (couldn't apply all chunks).

Build log: [build.log.zip](https://github.com/freeorion/freeorion-sdk/files/469966/build.log.zip)
`cmake/include/CMakeLists.txt.rej`: [CMakeLists.txt.rej.1.zip](https://github.com/freeorion/freeorion-sdk/files/469968/CMakeLists.txt.rej.1.zip)
`cmake/libpython/CMakeLists.txt.rej`: [CMakeLists.txt.rej.2.zip](https://github.com/freeorion/freeorion-sdk/files/469969/CMakeLists.txt.rej.2.zip)

**Comment by adrianbroher** [comment]
Rebased to latest master and updated broken patches in the process.

**Comment by adrianbroher** [comment]
Again rebased and added some patches to python-cmake.

**Comment by adrianbroher** [comment]
Missed a file.

**Comment by Vezzra** [comment]
Hm, doesn't seem to have changed much...

Build log and sdk layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/473400/Archiv.zip)

**Comment by adrianbroher** [comment]
Frameworks can only be created with shared libraries.  Cmake-python changed the option name to select the shared or static build.  Rebased and updated patches to use the correct option name.

**Comment by Vezzra** [comment]
Ok, now the Python frameworks gets created, at least partially. But it looks like not all of the Python stuff gets put into the framework package, but kind of scattered around (I think that's more or less the point where we were last time).

And the SDK build process still aborts with the same errors when building boost, so SDL, freetype etc. doesn't get build at all.

Build log and SDK layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/474390/Archiv.zip)

**Comment by adrianbroher** [comment]
Python headers should be installed into the framwork now.

**Comment by Vezzra** [comment]
Yep, the Python headers are now installed into the framework. Everything else apparently as before. Still Python stuff elsewhere (bin, include, lib, share).

As usual, build log and SDK layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/476723/Archiv.zip)

**Comment by adrianbroher** [comment]
Give it another try.

**Comment by adrianbroher** [comment]
Boost should now be able to find the python framework.

**Comment by Vezzra** [comment]
Now I get errors when Python is being build:
[build.log.zip](https://github.com/freeorion/freeorion-sdk/files/478610/build.log.zip)
[CMakeError.log.zip](https://github.com/freeorion/freeorion-sdk/files/478608/CMakeError.log.zip)
[CMakeOutput.log.zip](https://github.com/freeorion/freeorion-sdk/files/478609/CMakeOutput.log.zip)

**Comment by adrianbroher** [comment]
Sorry, for some reason I created a broken patch by adding useless string into some CMake files.  Should be fixed now.

**Comment by Vezzra** [comment]
Python build still fails, but with a different error now: [build.log.zip](https://github.com/freeorion/freeorion-sdk/files/478620/build.log.zip)

**Comment by adrianbroher** [comment]
Should be fixed now.

**Comment by Vezzra** [comment]
You didn't push any new commits...

**Comment by adrianbroher** [comment]
> You didn't push any new commits...

Now I did. =)

**Comment by Vezzra** [comment]
Looks like progress, but the Python framework still does not get produced correctly. Now I've two Python.framework bundles, one in the Frameworks dir as it should, but another one in the dependencies root dir. Each one holds some of the python stuff.

And building boost also still gives errors.

Build log and SDK layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/479702/Archiv.zip)

**Comment by adrianbroher** [comment]
Should be fixed now.

**Comment by Vezzra** [comment]
Ok, looks like a major breakthrough. AFAICT the cmake script completed this time, and the entire dependencies seem to have been built. The resulting layout still isn't identical to that of the current SDK, and trying to build FO with that SDK gives errors.

SDK build log and layout: [Archiv.zip](https://github.com/freeorion/freeorion-sdk/files/482818/Archiv.zip)
FO build log: [fo_build.log.zip](https://github.com/freeorion/freeorion-sdk/files/482822/fo_build.log.zip)

**Comment by adrianbroher** [comment]
```
/Users/user/SoftwareProjekte/FO/test-sdk/GG/src/GUI.cpp:28:10: fatal error: 'GG/Config.h' file not found
#include <GG/Config.h>
```

I'm wondering why this file is part of the SDK.  The MSVC has it's own copy inside the msvc2013 directory and CMake configures it at build time (as it is supposed to be used anyway).  Can you move that file into the freeorion repository and update the project files accordingly?

```
In file included from /Users/user/SoftwareProjekte/FO/test-sdk/Xcode/dep/include/boost/python/detail/prefix.hpp:13:
/Users/user/SoftwareProjekte/FO/test-sdk/Xcode/dep/include/boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found                                           
#include <pyconfig.h>
```

Can you check if the Python framework Headers directory is a symlink and if it is where it is pointing to?

The problem with freetype2 is because of the installation location for ft2build.h is different.  I need some time to check how it is done properly.

**Comment by Vezzra** [comment]
> I'm wondering why this file is part of the SDK. The MSVC has it's own copy inside the msvc2013 directory and CMake configures it at build time (as it is supposed to be used anyway). Can you move that file into the freeorion repository and update the project files accordingly?

Well, is there any point in maintaining multiple separate copies of that file outside the GG tree at all? I've taken a look at that file, and see no reason to keep an extra copy for each platform. So I propose to just move it to `GG/GG/Config.h` and remove it from all other locations - @geoffthemedio?

> Can you check if the Python framework Headers directory is a symlink and if it is where it is pointing to?

I assume you mean the Python framework as it is in the current SDK. These are the contents of its root directory (`ls -l` output):
```
lrwxr-xr-x  1 user  staff   24  8 Sep  2014 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 user  staff   23  8 Sep  2014 Python -> Versions/Current/Python
lrwxr-xr-x  1 user  staff   26  8 Sep  2014 Resources -> Versions/Current/Resources
drwxr-xr-x  5 user  staff  170 21 Feb  2015 Versions
```
So yes, it's a symlink and points to `Versions/Current/Headers`. This again is a symlink, pointing to `include/python2.7`:
```
lrwxr-xr-x   1 user  staff       17  8 Sep  2014 Headers -> include/python2.7
```

**Comment by adrianbroher** [comment]
> I assume you mean the Python framework as it is in the current SDK. 

Sorry, I meant the cmake generated one.

You can do `find . -type l -ls` inside the INSTALL directory.

Also an output of md5sums `find . -exec md5sum {} \;` would be great to identify config files that are off by content.

**Comment by Vezzra** [comment]
```
$ find . -type l -ls
14829363        8 lrwxr-xr-x    1 user             staff                  24 20 Sep 15:09 ./dep/Frameworks/Ogg.framework/Headers -> Versions/Current/Headers
14829364        8 lrwxr-xr-x    1 user             staff                  20 20 Sep 15:09 ./dep/Frameworks/Ogg.framework/Ogg -> Versions/Current/Ogg
14829365        8 lrwxr-xr-x    1 user             staff                  26 20 Sep 15:09 ./dep/Frameworks/Ogg.framework/Resources -> Versions/Current/Resources
14829375        8 lrwxr-xr-x    1 user             staff                   5 20 Sep 15:09 ./dep/Frameworks/Ogg.framework/Versions/Current -> 1.3.2
14846553        8 lrwxr-xr-x    1 user             staff                  23 20 Sep 15:11 ./dep/Frameworks/Python.framework/Python -> Versions/Current/Python
14846554        8 lrwxr-xr-x    1 user             staff                  26 20 Sep 15:11 ./dep/Frameworks/Python.framework/Resources -> Versions/Current/Resources
14846562        8 lrwxr-xr-x    1 user             staff                   6 20 Sep 15:11 ./dep/Frameworks/Python.framework/Versions/2.7/bin/python2 -> python
14846563        8 lrwxr-xr-x    1 user             staff                   6 20 Sep 15:11 ./dep/Frameworks/Python.framework/Versions/2.7/bin/python2.7 -> python
14846558        8 lrwxr-xr-x    1 user             staff                   3 20 Sep 15:11 ./dep/Frameworks/Python.framework/Versions/Current -> 2.7
14918166        8 lrwxr-xr-x    1 user             staff                  24 20 Sep 15:24 ./dep/Frameworks/SDL2.framework/Headers -> Versions/Current/Headers
14918167        8 lrwxr-xr-x    1 user             staff                  26 20 Sep 15:24 ./dep/Frameworks/SDL2.framework/Resources -> Versions/Current/Resources
14918168        8 lrwxr-xr-x    1 user             staff                  21 20 Sep 15:24 ./dep/Frameworks/SDL2.framework/SDL2 -> Versions/Current/SDL2
14918255        8 lrwxr-xr-x    1 user             staff                   5 20 Sep 15:24 ./dep/Frameworks/SDL2.framework/Versions/Current -> 2.0.4
14830262        8 lrwxr-xr-x    1 user             staff                  24 20 Sep 15:09 ./dep/Frameworks/Vorbis.framework/Headers -> Versions/Current/Headers
14830263        8 lrwxr-xr-x    1 user             staff                  26 20 Sep 15:09 ./dep/Frameworks/Vorbis.framework/Resources -> Versions/Current/Resources
14830273        8 lrwxr-xr-x    1 user             staff                   5 20 Sep 15:09 ./dep/Frameworks/Vorbis.framework/Versions/Current -> 1.3.5
14830274        8 lrwxr-xr-x    1 user             staff                  23 20 Sep 15:09 ./dep/Frameworks/Vorbis.framework/Vorbis -> Versions/Current/Vorbis
14827226        8 lrwxr-xr-x    1 user             staff                  22 20 Sep 15:08 ./dep/lib/libopenal.1.dylib -> libopenal.1.17.2.dylib
14827227        8 lrwxr-xr-x    1 user             staff                  17 20 Sep 15:08 ./dep/lib/libopenal.dylib -> libopenal.1.dylib
14828773        8 lrwxr-xr-x    1 user             staff                  14 20 Sep 15:08 ./dep/lib/libpng.dylib -> libpng16.dylib
14828771        8 lrwxr-xr-x    1 user             staff                  22 20 Sep 15:08 ./dep/lib/libpng16.16.dylib -> libpng16.16.25.0.dylib
14828772        8 lrwxr-xr-x    1 user             staff                  17 20 Sep 15:08 ./dep/lib/libpng16.dylib -> libpng16.16.dylib
```
In the cmake generated SDK the `Headers` folder/symlink is missing, as you can see.

The `find . -exec md5sum {} \;` does not work in that form, I just get tons of this:
```
find: md5sum: No such file or directory
find: md5sum: No such file or directory
find: md5sum: No such file or directory
find: md5sum: No such file or directory
find: md5sum: No such file or directory
find: md5sum: No such file or directory
find: md5sum: No such file or directory
...
```

**Comment by adrianbroher** [comment]
> The `find . -exec md5sum {} \;` does not work in that form.

Seems like MacOSX doesn't provide the md5sum command in this form.  Instead you can use `md5 -r` so the find command would look like this: `find . -exec md5 -r {} \;`.

**Comment by Vezzra** [comment]
Et voilà: [md5.txt.zip](https://github.com/freeorion/freeorion-sdk/files/485913/md5.txt.zip)

**Comment by adrianbroher** [comment]
Closing this issue now and creating a PR instead.  Manually notifying about new commits is a PITA.
